import pandas as pd
import yfinance as yf
from datetime import datetime

# List of top 100 Indian stocks (NSE tickers)
tickers = [
    'SHRIRAMFIN.NS',
'BAJAJHLDNG.NS',
'CHOLAFIN.NS',
'BAJAJFINSV.NS',
'BAJFINANCE.NS',
'INDUSINDBK.NS',
'HINDALCO.NS',
'COALINDIA.NS',
'HDFCBANK.NS',
'SUNPHARMA.NS',
'ZOMATO.NS',
'AXISBANK.NS',
'JSWSTEEL.NS',
'ICICIGI.NS',
'NAUKRI.NS',
'NESTLEIND.NS',
'RELIANCE.NS',
'INDIGO.NS',
'BHARTIARTL.NS',
'ICICIBANK.NS',
'WIPRO.NS',
'POWERGRID.NS',
'TITAN.NS',
'ATGL.NS',
'SHREECEM.NS',
'ADANIPORTS.NS',
'SBILIFE.NS',
'DRREDDY.NS',
'TATACONSUM.NS',
'INFY.NS',
'BRITANNIA.NS',
'ZYDUSLIFE.NS',
'ADANIENT.NS',
'HAL.NS',
'ADANIENSOL.NS',
'LODHA.NS',
'TCS.NS',
'JINDALSTEL.NS',
'ITC.NS',
'TATASTEEL.NS',
'HINDUNILVR.NS',
'HDFCLIFE.NS',
'BANKBARODA.NS',
'PFC.NS',
'DMART.NS',
'SBIN.NS',
'GODREJCP.NS',
'UNITDSPR.NS',
'UNIONBANK.NS',
'KOTAKBANK.NS',
'ADANIPOWER.NS',
'BOSCHLTD.NS',
'HCLTECH.NS',
'MARUTI.NS',
'AMBUJACEM.NS',
'NTPC.NS',
'LT.NS',
'ASIANPAINT.NS',
'RECLTD.NS',
'APOLLOHOSP.NS',
'PIDILITIND.NS',
'ICICIPRULI.NS',
'TORNTPHARM.NS',
'PNB.NS',
'BEL.NS',
'TECHM.NS',
'LICI.NS',
'CIPLA.NS',
'NHPC.NS',
'JIOFIN.NS',
'TATAMOTORS.NS',
'DABUR.NS',
'ONGC.NS',
'IRFC.NS',
'DIVISLAB.NS',
'GAIL.NS',
'LTIM.NS',
'IRCTC.NS',
'ADANIGREEN.NS',
'VEDL.NS',
'EICHERMOT.NS',
'CANBK.NS',
'IOC.NS',
'GRASIM.NS',
'TVSMOTOR.NS',
'HEROMOTOCO.NS',
'MOTHERSON.NS',
'DLF.NS',
'BPCL.NS',
'JSWENERGY.NS',
'BAJAJ-AUTO.NS',
'M&M.NS',
'TRENT.NS',
'TATAPOWER.NS',
'ABB.NS',
'SIEMENS.NS',
'BHEL.NS',
'ULTRACEMCO.NS',
'HAVELLS.NS',
'VBL.NS',

    # Add more tickers to reach 100
]

# Download the closing prices
data = yf.download(tickers, start='2024-02-26', end='2025-02-26')['Close']

# Generate a dynamic file name with timestamp
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
file_name = f"Outputs/csv/data_{timestamp}.csv"

# Save to CSV with the dynamic filename
data.to_csv(file_name)

print(f"Data saved as {file_name}")
