import pandas as pd
import yfinance as yf
from datetime import datetime

# List of top 100 Indian stocks (NSE tickers)
tickers = [
    'NIFTYBEES.NS', 'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'INFY.NS', 'ICICIBANK.NS',
            'HINDUNILVR.NS', 'KOTAKBANK.NS', 'AXISBANK.NS', 'LT.NS', 'MARUTI.NS', 'SBIN.NS',
            'BAJFINANCE.NS', 'ASIANPAINT.NS', 'HDFC.NS', 'ADANIENT.NS', 'BHARTIARTL.NS',
            'JSWSTEEL.NS', 'ULTRACEMCO.NS', 'ONGC.NS', 'POWERGRID.NS', 'APOLLOHOSP.NS',
            'CIPLA.NS', 'DRREDDY.NS', 'GRASIM.NS', 'HDFCLIFE.NS', 'INDUSINDBK.NS',
            'M&M.NS', 'TECHM.NS', 'UPL.NS', 'WPRO.NS', 'TITAN.NS', 'NESTLEIND.NS',
            'BAJAJFINSV.NS','TATAMOTORS.NS','HEROMOTOCO.NS','ITC.NS', 'BRITANNIA.NS',
            'NTPC.NS', 'TATAPOWER.NS', 'HCLTECH.NS', 'ADANIPORTS.NS', 'DIVISLAB.NS',
            'BAJAJHLDNG.NS', 'SBI.NS', 'SUNPHARMA.NS', 'HDFCAMC.NS','PIDILITIND.NS',
            'JSWENERGY.NS','SRF.NS','COLPAL.NS','DLF.NS','ICICIPRMF.NS','LTI.NS',
            'BHARATFORG.NS','CROMPTON.NS','PEL.NS','SAIL.NS','VEDL.NS','MGL.NS',
            'AARTIIND.NS','ABBOTINDIA.NS','ACC.NS','ALKEM.NS','AMBUJACEM.NS',
            'APLAPOLLO.NS','ARVINDKFASN.NS','ASHOKLEY.NS','AUROPHARMA.NS','BALKRISHIND.NS',
            'BANDHANBNK.NS','BANKBARODA.NS','BATAINDIA.NS','BEL.NS','BHARATFIN.NS',
            'BPCL.NS','BSOFT.NS','CANBK.NS','CHOLAFIN.NS','CONCOR.NS','COROMANDEL.NS',
            'DABUR.NS','DALBHARAT.NS','DEEPAKNTR.NS','DHANI.NS','DIXON.NS','EICHERMOT.NS',
            'ESCORTS.NS','FEDERALBNK.NS','GAIL.NS','GLENMARK.NS','GMRINFRA.NS','GODREJCP.NS',
            'GODREJPROP.NS','GRANULES.NS','HAVELLS.NS','HCLTECH.NS','HDFC.NS','HDFCLIFE.NS',
            'HEG.NS','HEXAWARE.NS','HINDALCO.NS','HINDCOPPER.NS','HINDMOTORS.NS','HINDUNILVR.NS',
            'IDFCFIRSTB.NS','IGL.NS','INDIGO.NS','INDUSINDBK.NS','INFY.NS','INTELLECT.NS',
            'IOB.NS','IOC.NS','IPCALAB.NS','IRCTC.NS','ISEC.NS','ITC.NS','JINDALSTEL.NS',
            'JUBLFOOD.NS','JUSTDIAL.NS','JYOTHYLAB.NS','KANSAINER.NS','KARURVYSYA.NS',
            'KCP.NS','KPITTECH.NS','KRBL.NS','LAURUSLABS.NS','LICHSGFIN.NS','LUPIN.NS',
            'M&M.NS','M&MFIN.NS','MAHINDRA.NS','MANAPPURAM.NS','MANKIND.NS','MASTEK.NS',
            'MAXHEALTH.NS','MCDOWELL.NS','MFSL.NS','MINDTREE.NS','MPHASIS.NS','MRF.NS',
            'MUTHOOTFIN.NS','NATCOPHARMA.NS','NAVINFLUOR.NS','NBCC.NS','NCC.NS','NESCO.NS',
            'NMDC.NS','NOCIL.NS','OFSS.NS','OIL.NS','OMAXAUTO.NS','ORIENTCEM.NS','PAGEIND.NS',
            'PEL.NS','PETRONET.NS','PFC.NS','PGIL.NS','PHOENIXLTD.NS','POLYCAB.NS','POWERGRID.NS',
            'PVR.NS','RADICO.NS','RAIN.NS','RAMCOCEM.NS','RBLBANK.NS','RECLTD.NS','RELIANCE.NS',
            'REPRO.NS','RIL.NS','RVNL.NS','SANOFI.NS','SBILIFE.NS','SHREECEM.NS','SRTRANSFIN.NS',
            'STAR.NS','STRIDES.NS','SUZLON.NS','SYNGENE.NS','TATACHEM.NS','TATACONSUM.NS',
            'TATAPOWER.NS','TATVACHINT.NS','TBIL.NS','TCS.NS','TECHM.NS','THERMAX.NS',
            'TIINDIA.NS','TITAN.NS','TORNTPHARM.NS','TORNTPOWER.NS','TRENT.NS','TRIVENI.NS',
            'TTML.NS','UBL.NS','ULTRACEMCO.NS','UNIONBANK.NS','UPL.NS','VAISHALI.NS',
            'VBL.NS','VEDL.NS','VINLAP.NS','VIPIND.NS','VOLTAS.NS','VRLLOG.NS','WHIRLPOOL.NS',
            'WIPRO.NS','YESBANK.NS','ZEEL.NS','ZOMATO.NS'
]

# Download the closing prices
data = yf.download(tickers, start='2023-02-13', end='2025-02-13')['Close']

# Generate a dynamic file name with timestamp
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
file_name = f"Outputs/csv/data_{timestamp}.csv"

# Save to CSV with the dynamic filename
data.to_csv(file_name)

print(f"Data saved as {file_name}")
